# -*- coding: utf-8 -*-
"""Untitled15.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lOYeg2WxsFsAWZ-m9t6Zx50mFrtAlXnM
"""

import streamlit as st

# ---------------- PAGE CONFIG ----------------
st.set_page_config(
    page_title="Crop Recommendation System",
    layout="wide"
)

# ---------------- CUSTOM CSS ----------------
st.markdown("""
<style>
.card {
    background-color: #111827;
    padding: 20px;
    border-radius: 15px;
    box-shadow: 0 4px 10px rgba(0,0,0,0.3);
    color: white;
    margin-bottom: 20px;
}
.title {
    font-size: 30px;
    font-weight: 700;
    text-align: center;
}
.subtitle {
    text-align: center;
    color: #9CA3AF;
    margin-bottom: 30px;
}
</style>
""", unsafe_allow_html=True)

# ---------------- LEFT SIDE (SIDEBAR) ----------------
st.sidebar.header("🌱 Soil Parameters")
N = st.sidebar.slider("Nitrogen (N)", 0, 140, 50)
P = st.sidebar.slider("Phosphorus (P)", 0, 145, 50)
K = st.sidebar.slider("Potassium (K)", 0, 205, 50)

st.sidebar.header("🌦 Climate Parameters")
temperature = st.sidebar.slider("Temperature (°C)", 0.0, 50.0, 25.0)
humidity = st.sidebar.slider("Humidity (%)", 0.0, 100.0, 70.0)
rainfall = st.sidebar.slider("Rainfall (mm)", 0.0, 300.0, 200.0)
ph = st.sidebar.slider("pH Value", 0.0, 14.0, 6.5)

# ---------------- MAIN PAGE (RIGHT SIDE) ----------------
st.markdown("<div class='title'>🌾 Crop Recommendation System</div>", unsafe_allow_html=True)
st.markdown("<div class='subtitle'>Machine Learning based crop recommendation</div>", unsafe_allow_html=True)

col1, col2 = st.columns(2)

with col1:
    st.markdown(f"""
    <div class="card">
        <h3>📊 Entered Values Overview</h3>
        <p>🌡 Temperature: {temperature} °C</p>
        <p>💧 Humidity: {humidity} %</p>
        <p>🌧 Rainfall: {rainfall} mm</p>
        <p>🧪 pH Value: {ph}</p>
    </div>
    """, unsafe_allow_html=True)

with col2:
    st.markdown(f"""
    <div class="card">
        <h3>🌱 Soil Health</h3>
        <p>🧬 Nitrogen (N): {N}</p>
        <p>🧬 Phosphorus (P): {P}</p>
        <p>🧬 Potassium (K): {K}</p>
        <p>🧪 pH Value: {ph}</p>
    </div>
    """, unsafe_allow_html=True)

# ---------------- BUTTON ----------------
st.markdown("---")
if st.button("🌾 Recommend Crop"):
    st.success("✅ Crop recommendation will be shown here!")