# -*- coding: utf-8 -*-
"""Untitled16.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1yM4baKJ2Tly07G-EoNeXiVjdcif_THEr
"""

import streamlit as st
import pickle
import pandas as pd

# Page config
st.set_page_config(
    page_title="Crop Recommendation System",
    page_icon="🌱",
    layout="wide"
)

# Load model
with open("crop_model.pkl", "rb") as f:
    model = pickle.load(f)

# Title
st.markdown(
    "<h1 style='text-align:center;'>🌾 Crop Recommendation System</h1>"
    "<p style='text-align:center;'>Machine Learning based crop suggestion using soil & climate data</p>",
    unsafe_allow_html=True
)

# Sidebar inputs
st.sidebar.header("🌱 Soil Parameters")
N = st.sidebar.slider("Nitrogen (N)", 0, 140, 50)
P = st.sidebar.slider("Phosphorus (P)", 0, 145, 50)
K = st.sidebar.slider("Potassium (K)", 0, 205, 50)
ph = st.sidebar.slider("pH value", 0.0, 14.0, 6.5)

st.sidebar.header("🌦️ Climate Parameters")
temperature = st.sidebar.slider("Temperature (°C)", 0.0, 50.0, 25.0)
humidity = st.sidebar.slider("Humidity (%)", 0.0, 100.0, 70.0)
rainfall = st.sidebar.slider("Rainfall (mm)", 0.0, 300.0, 200.0)

# Input DataFrame
input_df = pd.DataFrame({
    "N": [N],
    "P": [P],
    "K": [K],
    "temperature": [temperature],
    "humidity": [humidity],
    "ph": [ph],
    "rainfall": [rainfall]
})

# Layout
col1, col2 = st.columns(2)

with col1:
    st.subheader("📊 Entered Values Overview")
    st.metric("Temperature (°C)", temperature)
    st.metric("Humidity (%)", humidity)
    st.metric("Rainfall (mm)", rainfall)

with col2:
    st.subheader("🧪 Soil Health")
    st.metric("Nitrogen (N)", N)
    st.metric("Phosphorus (P)", P)
    st.metric("Potassium (K)", K)
    st.metric("pH value", ph)

# Prediction
st.markdown("---")
if st.button("🌾 Recommend Crop"):
    prediction = model.predict(input_df)[0]
prediction = label_encoder.inverse_transform([prediction])[0]

st.success(f"✅ Recommended Crop: **{prediction.upper()}**")