# -*- coding: utf-8 -*-
"""Untitled17.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cHG-sCTLG4dzFkNfqQ5C_qYen-HEi79J
"""

import streamlit as st
import pandas as pd
import pickle

# ================= LOAD MODEL =================
with open("model.pkl", "rb") as f:
    model = pickle.load(f)

# ================= PAGE CONFIG =================
st.set_page_config(
    page_title="Crop Recommendation System",
    page_icon="🌱",
    layout="wide"
)

st.title("🌾 Crop Recommendation System")
st.write("Enter soil and climate parameters to get the best crop recommendation.")

# ================= SIDEBAR INPUTS =================
st.sidebar.header("🌱 Soil Parameters")

N = st.sidebar.slider("Nitrogen (N)", 0, 200, 131)
st.sidebar.write(f"Selected Nitrogen (N): **{N}**")

P = st.sidebar.slider("Phosphorus (P)", 0, 200, 136)
st.sidebar.write(f"Selected Phosphorus (P): **{P}**")

K = st.sidebar.slider("Potassium (K)", 0, 200, 50)
st.sidebar.write(f"Selected Potassium (K): **{K}**")

ph = st.sidebar.slider("pH value", 0.0, 14.0, 6.5)
st.sidebar.write(f"Selected pH value: **{ph}**")

st.sidebar.header("🌤 Climate Parameters")

temperature = st.sidebar.slider("Temperature (°C)", 0.0, 50.0, 25.0)
st.sidebar.write(f"Temperature: **{temperature} °C**")

humidity = st.sidebar.slider("Humidity (%)", 0.0, 100.0, 70.0)
st.sidebar.write(f"Humidity: **{humidity}%**")

rainfall = st.sidebar.slider("Rainfall (mm)", 0.0, 300.0, 200.0)
st.sidebar.write(f"Rainfall: **{rainfall} mm**")

# ================= INPUT DATAFRAME =================
input_df = pd.DataFrame({
    "N": [N],
    "P": [P],
    "K": [K],
    "temperature": [temperature],
    "humidity": [humidity],
    "ph": [ph],
    "rainfall": [rainfall]
})

st.subheader("📊 Input Parameters")
st.dataframe(input_df, use_container_width=True)

# ================= PREDICTION =================
if st.button("🌱 Recommend Crop"):
    try:
        prediction = model.predict(input_df)[0]  # ✅ correct
        st.success(f"✅ Recommended Crop: **{prediction.upper()}**")
    except Exception as e:
        st.error("❌ Error during prediction")
        st.write(e)